###get all users
GET http://localhost:5500/users

###get one user
GET http://localhost:5500/users/65eb3b483a7d59cf53ea2002

###create new user
POST http://localhost:5500/users HTTP/1.1
content-type: application/json

{
"firstName": "Aeryn",
"lastName": "Suun",
"email": "peacekeeper@moya.com",
"password": "Moya4Win"
}


###update user
PUT http://localhost:5500/users/65eb3b393a7d59cf53ea11a4 HTTP/1.1
content-type: application/json

{ 
"firstName": "Curran",
"lastName": "Lennart",
"email": "curran@packHQ.com",
"password": "Be@stLord"
}

###Delete user
DELETE http://localhost:5500/users/65ef66d2d23f8bf0bf1f32e3 HTTP/1.1


###get all books
GET http://localhost:5500/books

###get one book
GET http://localhost:5500/books/65eba757c579ef38e46b12c1

###create new book
POST http://localhost:5500/books HTTP/1.1
content-type: application/json

{
    "title": "Original Grace",
    "author": "Adam Miller",
    "genre": "Spiritual",
    "pageCount": "144",
    "published": "2022",
    "printType": "hardback",
    "readStatus": "unread"

}


###update book
PUT http://localhost:5500/books/65eba757c579ef38e46b12c1 HTTP/1.1
content-type: application/json

{ 
    "title": "The Law of Love",
    "author": "Steve Young",
    "genre": "Religious",
    "pageCount": "208",
    "published": "2002",
    "printType": "ebook",
    "readStatus": "read"

}

###Delete book
DELETE http://localhost:5500/books/65ef699c2d3d0c59c2a7a1b4 HTTP/1.1
